declare const __eval__: typeof eval;
export { __eval__ as eval };
export { default as isFinite } from '@wareset-utilites/lang/isFinite';
export { default as isNaN } from '@wareset-utilites/lang/isNaN';
export { default as parseFloat } from '@wareset-utilites/lang/parseFloat';
export { default as parseInt } from '@wareset-utilites/lang/parseInt';
export { default as decodeURI } from '@wareset-utilites/lang/decodeURI';
export { default as decodeURIComponent } from '@wareset-utilites/lang/decodeURIComponent';
export { default as encodeURI } from '@wareset-utilites/lang/encodeURI';
export { default as encodeURIComponent } from '@wareset-utilites/lang/encodeURIComponent';
export { default as Object } from '@wareset-utilites/object/Object';
export { default as Function } from '@wareset-utilites/lang/Function';
export { default as Boolean } from '@wareset-utilites/lang/Boolean';
declare const __Symbol__: SymbolConstructor;
export { __Symbol__ as Symbol };
export { ErrorClass as Error, EvalErrorClass as EvalError, RangeErrorClass as RangeError, ReferenceErrorClass as ReferenceError, SyntaxErrorClass as SyntaxError, TypeErrorClass as TypeError, URIErrorClass as URIError } from '@wareset-utilites/error';
declare const __setTimeout__: typeof setTimeout;
export { __setTimeout__ as setTimeout };
declare const __setInterval__: typeof setInterval;
export { __setInterval__ as setInterval };
declare const __Infinity__: number;
export { __Infinity__ as Infinity };
declare const __NaN__: number;
export { __NaN__ as NaN };
declare let __undefined__: undefined;
export { __undefined__ as undefined };
export { default as Number } from '@wareset-utilites/number/Number';
declare const __Math__: Math;
export { __Math__ as Math };
declare const __Date__: DateConstructor;
export { __Date__ as Date };
export { default as String } from '@wareset-utilites/string/String';
export { default as RegExp } from '@wareset-utilites/lang/RegExp';
export { default as Array } from '@wareset-utilites/array/Array';
declare const __Int8Array__: Int8ArrayConstructor;
export { __Int8Array__ as Int8Array };
declare const __Uint8Array__: Uint8ArrayConstructor;
export { __Uint8Array__ as Uint8Array };
declare const __Uint8ClampedArray__: Uint8ClampedArrayConstructor;
export { __Uint8ClampedArray__ as Uint8ClampedArray };
declare const __Int16Array__: Int16ArrayConstructor;
export { __Int16Array__ as Int16Array };
declare const __Uint16Array__: Uint16ArrayConstructor;
export { __Uint16Array__ as Uint16Array };
declare const __Int32Array__: Int32ArrayConstructor;
export { __Int32Array__ as Int32Array };
declare const __Uint32Array__: Uint32ArrayConstructor;
export { __Uint32Array__ as Uint32Array };
declare const __Float32Array__: Float32ArrayConstructor;
export { __Float32Array__ as Float32Array };
declare const __Float64Array__: Float64ArrayConstructor;
export { __Float64Array__ as Float64Array };
declare const __Map__: MapConstructor;
export { __Map__ as Map };
declare const __Set__: SetConstructor;
export { __Set__ as Set };
declare const __WeakMap__: WeakMapConstructor;
export { __WeakMap__ as WeakMap };
declare const __WeakSet__: WeakSetConstructor;
export { __WeakSet__ as WeakSet };
declare const __ArrayBuffer__: ArrayBufferConstructor;
export { __ArrayBuffer__ as ArrayBuffer };
declare const __DataView__: DataViewConstructor;
export { __DataView__ as DataView };
declare const __JSON__: JSON;
export { __JSON__ as JSON };
